### ISSUE TITLE
ItemStack#getEnchantments() throws NullPointerException due to null delegate field

### ISSUE THREAD

**Issue by mdeancline** [MockBukkit/MockBukkit#1102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.20

### Describe the bug

This issue occurs when retrieving enchantments from ``ItemStack``s that were created directly, as well as from ``ItemStack``s in inventory mocks.

Exception from ItemStackCreation_ItemStack_FailsOnPropertiesRetrieval:
```java
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getEnchantments()" because "this.craftDelegate" is null

	at org.bukkit.inventory.ItemStack.getEnchantments(ItemStack.java:378)
	at org.bukkit.inventory.ItemStack.getEnchantments(ItemStack.java:378)
	at io.github.eventiful.plugin.ItemStackPropertiesTest.assertPropertiesNotNull(ItemStackPropertiesTest.java:73)
	at io.github.eventiful.plugin.ItemStackPropertiesTest.ItemStackCreation_ItemStack_FailsOnPropertiesRetrieval(ItemStackPropertiesTest.java:44)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

Exception from ItemStackEquipmentRetrieval_EntityEquipmentMock_FailsOnPropertiesRetrieval:
```java
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getEnchantments()" because "this.craftDelegate" is null

	at org.bukkit.inventory.ItemStack.getEnchantments(ItemStack.java:378)
	at io.github.eventiful.plugin.PlayerInventoryMockTest.assertPropertiesNotNull(PlayerInventoryMockTest.java:59)
	at io.github.eventiful.plugin.PlayerInventoryMockTest.ItemStackEquipmentRetrieval_EntityEquipmentMock_FailsOnPropertiesRetrieval(PlayerInventoryMockTest.java:45)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

Exception from ItemStackEquipmentRetrieval_PlayerInventoryMock_FailsOnPropertiesRetrieval:
```java
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getEnchantments()" because "this.craftDelegate" is null

	at org.bukkit.inventory.ItemStack.getEnchantments(ItemStack.java:378)
	at io.github.eventiful.plugin.PlayerInventoryMockTest.assertPropertiesNotNull(PlayerInventoryMockTest.java:59)
	at io.github.eventiful.plugin.PlayerInventoryMockTest.ItemStackEquipmentRetrieval_PlayerInventoryMock_FailsOnPropertiesRetrieval(PlayerInventoryMockTest.java:53)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

I'm not sure why the other property methods don't throw a ``NullPointerException`` when the ``craftDelegate`` field is ``null``, given that they're delegated to it.

### Reproducible Test

```java
public class ItemStackPropertiesTest {
    private PlayerMock mockPlayer;
    private ZombieMock mockZombie;

    @Before
    public void setUp() {
        final ServerMock mockServer = MockBukkit.mock();
        mockPlayer = mockServer.addPlayer("");

        final WorldMock mockWorld = mockPlayer.getWorld();
        mockZombie = (ZombieMock) mockWorld.spawn(Vector.getRandom().toLocation(mockWorld), Zombie.class);
    }

    @After
    public void tearDown() {
        MockBukkit.unmock();
    }

    @Test
    public void ItemStackCreation_ItemStack_FailsOnPropertiesRetrieval() {
        assertPropertiesNotNull(newEnchantedDiamondHelmet());
    }

    @Test
    public void ItemStackCreation_ItemStackMock_FailsOnPropertiesRetrieval() {
        assertPropertiesNotNull(new ItemStackMock(newEnchantedDiamondHelmet()));
    }

    @Test
    public void ItemStackEquipmentRetrieval_EntityEquipmentMock_FailsOnPropertiesRetrieval() {
        final EntityEquipment equipment = Objects.requireNonNull(mockZombie.getEquipment());
        equipment.setHelmet(newEnchantedDiamondHelmet());

        assertPropertiesNotNull(equipment.getItem(EquipmentSlot.HEAD));
    }

    @Test
    public void ItemStackEquipmentRetrieval_PlayerInventoryMock_FailsOnPropertiesRetrieval() {
        final EntityEquipment equipment = Objects.requireNonNull(mockPlayer.getEquipment());
        equipment.setHelmet(newEnchantedDiamondHelmet());

        assertPropertiesNotNull(equipment.getItem(EquipmentSlot.HEAD));
    }

    private @NotNull ItemStack newEnchantedDiamondHelmet() {
        final ItemStack helmet = new ItemStack(Material.DIAMOND_HELMET);
        helmet.addEnchantment(Enchantment.AQUA_AFFINITY, 1);
        helmet.addEnchantment(Enchantment.THORNS, 1);
        return helmet;
    }

    private void assertPropertiesNotNull(final ItemStack itemStack) {
        assertNotNull(itemStack.getItemMeta());
        assertNotNull(itemStack.getType());
        assertNotNull(itemStack.getEnchantments());
    }
}
```

**Comment by mdeancline** [comment]
I should also mention that this issue is occurring with ``ItemStackMock``. I've updated the reproducible test to illustrate the problem.

**Comment by Thorinwasher** [comment]
I'm confused about this behavior. Just to be sure, are you also on the latest version of mockbukkit? (Please write the version here) In that case it would cause weird issues, as the latest version of mockbukkit only works for 1.21.1

**Comment by thelooter** [comment]
This behaviour occurs since we haven't implemented this Method ourselves. Feel free to contribute a PR to fix this, or wait for us to fix it in the next few days
