### ISSUE TITLE
External plugin compatibility

### ISSUE THREAD

**Issue by TheDrakonir** [MockBukkit/MockBukkit#149]
Hey there,
we wanted to start using MockBukkit for unit testing on a small scale project for the usual reasons. So I started following the guide in the readme and setup MockBukkit accordingly. But when trying to load third party plugins (e.g. PlaceholderApi) that our plugin interfaces with problems came up. Here's the stacktrace for your records (we are targeting spigot 1.16 & I'm using the 1.16 release):
```
org.bukkit.plugin.InvalidPluginException: This version of MockBukkit required API 1.15
        at be.seeseemelk.mockbukkit.MockUnsafeValues.checkSupported(MockUnsafeValues.java:74)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
        at be.seeseemelk.mockbukkit.MockBukkit.loadJar(MockBukkit.java:132)
        at de.clymcity.clymcity.mock.util.ServerTest.setUp(ServerTest.java:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

So I investigated a bit deeper into the topic and noticed there is a check for the plugin `api-version` when loading a plugin that is located here [MockUnsafeValues.java](https://github.com/seeseemelk/MockBukkit/blob/v1.16/src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java).

It is directly comparing by the string "1.15" so there's no match for "1.16". However pushing the value up to "1.16" wouldn't work either, as these external plugins declare the api-version of `1.13` to state their backwards compatibility. If I understand threads like [that](https://www.spigotmc.org/threads/api-version-concerns-for-the-future.369826/) I found regarding the api-version correctly, then the implementation should allow any api-version that is below it's current version number, right? Like 1.13 is runnable on 1.16 (what is what we're doing), but 1.16 isn't on a 1.13 server.

I'm not as proficient with the project's code as you are, so I wonder if such behaviour would be feasible or are there any caveats to such approach?

Thanks for your time,
TheDrakonir

**Comment by TheBusyBiscuit** [comment]
Closing this since it was resolved via #150
