### ISSUE TITLE
NoSuchMethodError when initialising plugin

### ISSUE THREAD

**Issue by f0rbit** [MockBukkit/MockBukkit#226]
Trying to use MockBukkit-v1.16:1.0.0 to test my plugin, called Generator with JUnit 5. Inside my test file I have this code:
```java
public class TestPlugin {
    private static ServerMock server;
    private static Generator plugin;



    @BeforeAll
    static void setUp() {
        server = MockBukkit.mock();
        plugin = (Generator) MockBukkit.load(Generator.class);
    }

    @AfterAll
    static void teardown() {
        MockBukkit.unmock();
    }

    @Test
    void testFields() {
        Assertions.assertNotNull(Generator.getAPI());
        Assertions.assertNotNull(Generator.getInstance());

    }

    @Test
    void testCommands() {
        CommandSender sender = server.addPlayer();
        Assertions.assertAll(() -> {
            Assertions.assertTrue(server.dispatchCommand(sender, "gen 0"));
        }, () -> {
            Assertions.assertTrue(server.dispatchCommand(sender, "gen 2"));
        }, () -> {
            Assertions.assertTrue(server.dispatchCommand(sender, "gen clear"));
        }, () -> {
            Assertions.assertTrue(server.dispatchCommand(sender, "gen 0"));
        }, () -> {
            Assertions.assertTrue(server.dispatchCommand(sender, "gen tp"));
        });
    }
}

```

However, this code is giving an error whenever run:
```java
'void org.yaml.snakeyaml.TypeDescription.<init>(java.lang.Class, org.yaml.snakeyaml.nodes.Tag, java.lang.Class)'
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.TypeDescription.<init>(java.lang.Class, org.yaml.snakeyaml.nodes.Tag, java.lang.Class)'
	at org.yaml.snakeyaml.constructor.BaseConstructor.<init>(BaseConstructor.java:105)
	at org.yaml.snakeyaml.constructor.SafeConstructor.<init>(SafeConstructor.java:55)
	at org.yaml.snakeyaml.constructor.SafeConstructor.<init>(SafeConstructor.java:51)
	at org.bukkit.plugin.PluginDescriptionFile$1$1.<init>(PluginDescriptionFile.java:197)
	at org.bukkit.plugin.PluginDescriptionFile$1.initialValue(PluginDescriptionFile.java:197)
	at org.bukkit.plugin.PluginDescriptionFile$1.initialValue(PluginDescriptionFile.java:1)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:252)
	at be.seeseemelk.mockbukkit.plugin.PluginManagerMock.findPluginDescription(PluginManagerMock.java:377)
	at be.seeseemelk.mockbukkit.plugin.PluginManagerMock.loadPlugin(PluginManagerMock.java:352)
	at be.seeseemelk.mockbukkit.MockBukkit.load(MockBukkit.java:178)
	at be.seeseemelk.mockbukkit.MockBukkit.load(MockBukkit.java:163)
	at test.forbit.generator.TestPlugin.setUp(TestPlugin.java:23)
```

And this is my build.gradle
```gradle
import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id 'java'
    id 'java-library'
}

ext {
    lombokVersion = '1.18.20'
}

group = 'dev.forbit'
version = '1.6.2-SNAPSHOT'
jar.archiveBaseName='dark-generator'

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        name = 'spigotmc-repo'
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
    }
    maven {
        name = 'sonatype'
        url = 'https://oss.sonatype.org/content/groups/public/'
    }

    // FAWE
    maven {
        url = uri("https://mvn.intellectualsites.com/content/repositories/releases/")
    }
}

dependencies {
    compileOnly("org.projectlombok:lombok:${lombokVersion}")
    annotationProcessor("org.projectlombok:lombok:${lombokVersion}")
    implementation 'org.jetbrains:annotations:20.1.0'
    compile 'org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT'
    compile("com.intellectualsites.fawe:FAWE-Bukkit:1.16-637")
    compile project(":plugin-dark-world")
    compile project(":plugin-dark-spawners")
    implementation 'com.elmakers.mine.bukkit:EffectLib:8.0'
    compile 'org.junit.jupiter:junit-jupiter:5.7.2'
    testImplementation 'com.github.seeseemelk:MockBukkit-v1.16:1.0.0'

}

processResources {
    from(sourceSets.main.resources.srcDirs) {
        filter ReplaceTokens, tokens: [version: version]
    }
}
```

The source code for the whole plugin, and my entire project is available [here](https://github.com/TheDarkTurnip/dark-dungeon/tree/plugin/plugins/source%20code/dark-dungeon-multi/plugin-dark-generator)

I am 90% sure I'm doing something wrong but I can't tell what, since this seems to be working for everyone but me!

**Comment by TheBusyBiscuit** [comment]
Try to update MockBukkit first, latest version is `1.1.0` on `maven-central` at this time.

**Comment by f0rbit** [comment]
I've tried updating to the latest version `1.1.0` and also tried the latest git branch. After an entire day testing this out it seems to not be an issue with this plugin itself but rather with Bukkit's `PluginDescriptionFile` class. For some reason, it isn't accepting my some of my plugins `plugin.yml` files, but I am able to pass through something like this
```java

@BeforeAll
static void setUp() throws FileNotFoundException, InvalidDescriptionException {
    server = MockBukkit.mock();
    PluginDescriptionFile file = new PluginDescriptionFile("plugin-name", "test-version", "main-class");
    plugin = MockBukkit.loadWith(Generator.class, file);
}
```
and then the tests run normally, although I'm struggling to find a way to test commands now that they're not being defined inside the `plugin.yml`. 

This issue is no longer relevant to this repo, but thanks for helping :)

**Comment by seeseemelk** [comment]
Could you post you plugin's `plugin.yml`? This shouldn't normally be an issue unles the `plugin.yml` is invalid.
