### ISSUE TITLE
Cannot add player to server in 1.18

### ISSUE THREAD

**Issue by wvffle** [MockBukkit/MockBukkit#340]
Following minimal example does not seem to work for me:
```java
public class ExampleTest {
    ServerMock server;

    @BeforeEach
    void setup () {
        server = MockBukkit.mock();
        server.addPlayer(); // Fails here
    }

    @AfterEach
    void teardown () {
        MockBukkit.unmock();
    }

    @Test
    void exampleTest () {
        assertEquals(1, 1);
    }
}
```
It throws this error:
```
java.lang.AbstractMethodError: Receiver class be.seeseemelk.mockbukkit.MockUnsafeValues does not define or inherit an implementation of the resolved method 'abstract net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer legacyComponentSerializer()' of interface org.bukkit.UnsafeValues.

	at org.bukkit.event.player.PlayerJoinEvent.<init>(PlayerJoinEvent.java:23)
	at be.seeseemelk.mockbukkit.ServerMock.addPlayer(ServerMock.java:218)
	at be.seeseemelk.mockbukkit.ServerMock.addPlayer(ServerMock.java:234)
	at net.wvffle.mc.plugin.ExampleTest.setup(ExampleTest.java:19)
```

I'm using Paper API with MockBukkit 1.24.1 (1.25 does not seem to be in the maven repository)

```xml
<dependency>
    <groupId>io.papermc.paper</groupId>
    <artifactId>paper-api</artifactId>
    <version>1.18.2-R0.1-SNAPSHOT</version>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>com.github.seeseemelk</groupId>
    <artifactId>MockBukkit-v1.18</artifactId>
    <version>1.24.1</version>
    <scope>test</scope>
</dependency>
```

**Comment by wvffle** [comment]
Well, it boils down to #143
