### ISSUE TITLE
ServerMock#getItemFactory now returns ItemFactoryMock instead of ItemFactory

### ISSUE THREAD

**Issue by JorelAli** [MockBukkit/MockBukkit#862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.20

### Describe the bug

In b20d06e39e43f9858598cb045fd82a0a70594d28, the method signature for `getItemFactory()` was changed to return a `ItemFactoryMock` instead of a `ItemFactory`:

https://github.com/MockBukkit/MockBukkit/blob/b20d06e39e43f9858598cb045fd82a0a70594d28/src/main/java/be/seeseemelk/mockbukkit/ServerMock.java#L664-L668

This change breaks my test suite, where I have a custom class that extends `ServerMock`. Is there any particular reason why the method signature for `getItemFactory()` was made stricter than necessary, when using `ItemFactory` does the same thing given that `ItemFactoryMock` implements `ItemFactory`?

### Reproducible Test

1. Write the following class:

   ```java
   public class MyCustomServerMock extends ServerMock {
   
       @Override
       public ItemFactory getItemFactory() {
           return null;
       }
   
   }
   ```

2. Attempt to compile with the following dependency:

   ```xml
   <dependency>
       <groupId>com.github.seeseemelk</groupId>
       <artifactId>MockBukkit-v1.20</artifactId>
       <version>3.9.0</version>
   </dependency>
   ```

### Anything else?

```ini
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile (default-testCompile) on project commandapi-bukkit-test-tests: Compilation failure
/C:/Users/Jorel/Documents/GitHub/CommandAPI/commandapi-platforms/commandapi-bukkit/commandapi-bukkit-test/commandapi-bukkit-test-tests/src/test/java/dev/jorel/commandapi/test/CommandAPIServerMock.java:[150,28] getItemFactory() in dev.jorel.commandapi.test.CommandAPIServerMock cannot override getItemFactory() in be.seeseemelk.mockbukkit.ServerMock
  return type org.bukkit.inventory.ItemFactory is not compatible with be.seeseemelk.mockbukkit.inventory.ItemFactoryMock

        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:347)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
        at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
        at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
        at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
        at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:204)
        at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:78)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/C:/Users/Jorel/Documents/GitHub/CommandAPI/commandapi-platforms/commandapi-bukkit/commandapi-bukkit-test/commandapi-bukkit-test-tests/src/test/java/dev/jorel/commandapi/test/CommandAPIServerMock.java:[150,28] getItemFactory() in dev.jorel.commandapi.test.CommandAPIServerMock cannot override getItemFactory() in be.seeseemelk.mockbukkit.ServerMock
  return type org.bukkit.inventory.ItemFactory is not compatible with be.seeseemelk.mockbukkit.inventory.ItemFactoryMock

        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1310)
        at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:183)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
        ... 15 common frames omitted
```

**Comment by Insprill** [comment]
I believe it was necessary due to extra API we added in ItemFactoryMock. If that's not the case and ItemFactory would work, you can make a PR changing it back. Otherwise, is there a reason you can't change the definition in your server mock to return an ItemFactoryMock?

**Comment by JorelAli** [comment]
> I believe it was necessary due to extra API we added in ItemFactoryMock. 

If a user wanted to explicitly use `ItemFactoryMock`, they are able to cast `ItemFactory` to `ItemFactoryMock` and use the methods/features of `ItemFactoryMock`.

Due to this change, if a user wanted to use a custom implementation (or unmodifiable existing implementation) of `ItemFactory`, they have to extend `ItemFactoryMock`. This is not possible for instances of `ItemFactory` that cannot be modified by the user.

In my use case, my implementation of `getItemFactory` returns `CraftItemFactory.instance()`. I cannot make this object conform to `ItemFactoryMock` because it does not inherit from it, nor can I change this to inherit from it.

**Comment by JorelAli** [comment]
Because you're creating an API, you've effectively introduced a backwards-incompatible change by replacing `ItemFactory` with the more restrictive `ItemFactoryMock`. You are subclassing a well-established class that has a known standard (in this case you implement `Server`) and make it more restrictive than necessary to facilitate your own functionality.

If you wanted users to explicitly access MockBukkit's `ItemFactoryMock` class, you should create your own method, for example:

```java
@Override
public @NotNull ItemFactory getItemFactory()
{
	// Leave the original method untouched, so it can be overridden if necessary
	return factory;
}
	
public @NotNull ItemFactoryMock getMockBukkitItemFactory()
{
	// Create your own specific method, for ease-of-use
	return factory;
}
```

I've opened #864 for a minimal solution (reverting the original change) and I'll let you decide on whether you want to create MockBukkit-specific methods for any other implementations if necessary.

**Comment by Insprill** [comment]
Merged, thank you!
