### ISSUE TITLE
papermc serializeAsBytes not implemented for ItemStack

### ISSUE THREAD

**Issue by sowelipililimute** [MockBukkit/MockBukkit#896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

papermc `serializeAsBytes` and the corresponding `deserializeBytes` is not implemented for the MockBukkit ItemStack

```
==> X OrderSuite.basic serialization  0.074s be.seeseemelk.mockbukkit.UnimplementedOperationException: Not implemented
    at be.seeseemelk.mockbukkit.MockUnsafeValues.serializeItem(MockUnsafeValues.java:260)
    at org.bukkit.inventory.ItemStack.serializeAsBytes(ItemStack.java:726)
    at BallCore.Shops.SellOrderItemDescription.serialize$$anonfun$1(SellOrder.scala:49)
    at scala.Option.foreach(Option.scala:437)
    at BallCore.Shops.SellOrderItemDescription.serialize(SellOrder.scala:50)
    at OrderSuite.$init$$$anonfun$1(OrderSuite.scala:26)
```

**Comment by ens-gijs** [comment]
It looks like #1013 was (somewhat) a duplicate of #896 - with PR #1014 resolving item serialization via Map<String, Object> and added support for `serializeItem` in `UnsafeValuesMock` (which is what `ItemStack#serializeAsBytes` delegates to) but its current behavior does not match paper.

PR #1014 implements `UnsafeValuesMock#serializeItem` to marshal ConfigurationSerializable objects via BukkitObjectOutputStreamMock which marshals data via Map<String, Object> while paper is using binary NBT (GZIP'd).

The existing impl will support tests / SUT's that treat the binary data as a black-box but will not work for anyone who tries to parse that data outside of using `deserializeItem`.

Actually using NBT would mean adding, and maintaining, NBT conversions that don't currently exist and probably mirroring the data upgrade path too.

**Comment by 4everTheOne** [comment]
Fixed by https://github.com/MockBukkit/MockBukkit/issues/1013

**Comment by ens-gijs** [comment]
> Fixed by [#1013](https://github.com/MockBukkit/MockBukkit/issues/1013)

I suppose that's technically correct - but what's in place within MockBukkit can only support blackbox testing of flows which use both  `UnsafeValuesMock#serializeItem` and `deserializeItem` and CANNOT be used for testing any code which cares about the bytes themselves and needs to process the, what is supposed to be, binary NBT data directly.
